name: widgets
description: A new Flutter package project.
version: 0.0.9
author: 
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  intl: ^0.18.1
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
