name: core
description: A new Flutter package project.
version: 0.0.11
author: null
homepage: null

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies: 
  build_runner: ^2.3.3
  connectivity: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed: ^2.3.3
  http: ^0.13.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
